#!/usr/bin/env bash

function tests() {
  pytest "$1" --mocha
}

function test-coverage() {
  pytest --cov=yann tests/
}

function watch-tests() {
  pytest-watch "$1" -- --testmon --mocha
}

function release() {
  rm -rf ./dist
  rm -rf ./build
  python -m build
  twine upload dist/*
}

function serve-docs() {
  mkdocs serve
}

function deploy-docs() {
  mkdocs gh-deploy
}

if declare -f "$1" > /dev/null
then
  "$@"
else
  echo "'$1' is not a known function name" >&2
  exit 1
fi