id: briny-salty-mess
name: Dataset-BertClassifier
path: runs/bert_classifier/Dataset-BertClassifier/25-09-07T02:52:24
num_steps: 0
num_samples: 0
num_epochs: 0
batch_size: 8
device: cpu
time_created: 2025-09-07 02:52:24.232174
env:
  cwd: /Users/michalwolski/projects/yann
  arguments:
  - examples/bert_classifier.py
  - -e
  - '1'
  - -bs
  - '8'
  git_hash: 7d55f08
  python:
    executable: /Users/michalwolski/projects/yann/.venv/bin/python3
    version: 3.11.11 (main, Mar 17 2025, 21:33:08) [Clang 20.1.0 ]
    path:
    - /Users/michalwolski/projects/yann/examples
    - /Users/michalwolski/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python311.zip
    - /Users/michalwolski/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11
    - /Users/michalwolski/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/lib-dynload
    - /Users/michalwolski/projects/yann/.venv/lib/python3.11/site-packages
    - /var/folders/16/qqcqrk5d2c748c0t_fnps_g00000gn/T/tmpfjo890ul
  torch_version: !!python/object/new:torch.torch_version.TorchVersion
  - 2.6.0
  yann_version: 0.0.40
  hostname: Michals-MacBook-Pro.local
dataset:
  name: Dataset
  size: 25000
  num_classes: null
model:
  name: BertClassifier
  param_count: 109483778
  trainable_param_count: 109483778
