id: musty-zonal-ember
name: TensorDataset-NoneType
path: runs/TensorDataset-NoneType/25-09-07T00:41:41
num_steps: 0
num_samples: 0
num_epochs: 0
batch_size: null
device: mps
time_created: 2025-09-07 00:41:41.759608
env:
  cwd: /Users/michalwolski/projects/yann
  arguments:
  - /Users/michalwolski/projects/yann/.venv/bin/pytest
  - tests/test_trainer_comprehensive.py
  - -v
  git_hash: 7d55f08
  python:
    executable: /Users/michalwolski/projects/yann/.venv/bin/python3
    version: 3.11.11 (main, Mar 17 2025, 21:33:08) [Clang 20.1.0 ]
    path:
    - /Users/michalwolski/projects/yann
    - /Users/michalwolski/projects/yann/.venv/bin
    - /Users/michalwolski/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python311.zip
    - /Users/michalwolski/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11
    - /Users/michalwolski/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/lib-dynload
    - /Users/michalwolski/projects/yann/.venv/lib/python3.11/site-packages
    - /var/folders/16/qqcqrk5d2c748c0t_fnps_g00000gn/T/tmpwh013dr1
  torch_version: !!python/object/new:torch.torch_version.TorchVersion
  - 2.6.0
  yann_version: 0.0.40
  hostname: Michals-MacBook-Pro.local
dataset:
  name: TensorDataset
  size: 100
  num_classes: null
