id: doubtful-zesty-borer
name: CIFAR10-Stack
path: runs/CIFAR10-Stack/24-03-23T02:38:39
num_steps: 0
num_samples: 0
num_epochs: 0
batch_size: 32
device: mps
time_created: 2024-03-23 02:38:39.883385
env:
  cwd: /Users/michalwolski/projects/yann
  arguments:
  - examples/train_mnist.py
  git_hash: e831fca1cd13433ce828421e2597cd79c5c03b22
  python:
    executable: /Users/michalwolski/projects/yann/env/bin/python
    version: "3.9.6 (default, Aug 11 2023, 19:44:49) \n[Clang 15.0.0 (clang-1500.0.40.1)]"
    path:
    - /Users/michalwolski/projects/yann/examples
    - /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python39.zip
    - /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9
    - /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/lib-dynload
    - /Users/michalwolski/projects/yann/env/lib/python3.9/site-packages
    - /Users/michalwolski/projects/yann
  torch_version: !!python/object/new:torch.torch_version.TorchVersion
  - 2.2.1
  yann_version: 0.0.40
  hostname: Michals-MacBook-Pro.local
dataset:
  name: CIFAR10
  size: 50000
  num_classes: 10
model:
  name: Stack
  param_count: 21840
  trainable_param_count: 21840
